---
title: "EM611. Осень-зима 2018."
author: "Boris Demeshev"
output: html_document
lang: ru-RU
---


Курс эконометрики для магистерской программы финтех. Продолжительность — один семестр.

### Программа

1. МНК без вероятностей

  суть МНК, матричный дифференциал, геометрический смысл условий первого порядка,
  геометрический смысл транспонирования, матрица-шляпница, TSS, ESS, RSS.

2. SVD

  SVD применительно к МНК. SVD применительно к методу главных компонент.

3. МНК с предпосылками на ожидание и дисперсию.

  ожидание и ковариационная матрица от векторов, ожидание от квадратичной формы,
  теорема Гаусса-Маркова, геометрическое доказательство теоремы Гаусса-Маркова

4. Зоопарк распределений

  вероятностная дифференциальная форма, экспоненциальное, гамма, бета — через время ожидания,
  t, F, $\chi^2$ — через проекции

5. МНК с нормальными ошибками

  проверка гипотез об отдельном коэффициенте, проверка гипотез о нескольких линейных ограничениях,
  распределение R^2, TSS, RSS

6. Гетероскедастичность

  Кросс-валидация, состоятельные оценки для ковариационной матрицы. Идея GLS.

7. Метод максимального правдоподобия

  Теоретические свойства. Тесты LR, LM, Wald.

8. Логистическая регрессия.

  Модель, свойства оценок.

9. Вольная программа, немного учитывающая пожелания слушателей :


### Система оценивания

* Домашнее задание — 20%
* Письменная контрольная — 30%
* Письменный экзамен — 50%

### Ссылки:

* [оценки-2018](https://docs.google.com/spreadsheets/d/1Da3y6Tq-GEtGftxtjGG-iQ77-mtY4W9HfN8Wewqxv7U/edit?usp=sharing)

* [github-репозиторий](https://github.com/bdemeshev/em611) курса EM611: свалка файлов
* [Курс EM301](http://bdemeshev.github.io/em301/): бакалавриат факультета экономики вшэ
* [Задачи с кр EM301](https://github.com/bdemeshev/metrics_hse_exams/raw/master/metrics_hse_exams.pdf)
* [Задачи к семинарам](https://github.com/bdemeshev/metrics_pro/raw/master/metrics_pro.pdf) EM301
* Частичный [Конспект-2017 by Андрей Коломиец](https://github.com/bdemeshev/em611/raw/master/2017/metrics_ak.docx). Есть немного ошибок, будьте бдительны! Частичный [лог курса-2017](https://bdemeshev.github.io/em611/index_2017_2018.html)


Если нужна одна книжка:

Stachursky, Primer in econometric theory. [Слайды и часть глав](http://johnstachurski.net/emet.html).


### Конспекты:

* Шаблон, [tex](https://github.com/bdemeshev/em611/blob/master/2017/note_template/note_template.tex) и [pdf](https://github.com/bdemeshev/em611/raw/master/2017/note_template/note_template.pdf) для конспектирования лекций, [картинки для МНК](https://github.com/olyagnilova/gauss-markov-pythagoras) из работы Оли Гниловой, их можно свободно использовать.

* Встреча 1. МНК без вероятностей. Зато с матрицами :)

    - Конспект Севы Овечкина: [pdf](https://github.com/bdemeshev/em611/raw/master/2018/notes/seminar_01.pdf), [tex](https://github.com/bdemeshev/em611/raw/master/2018/notes/seminar_01.tex)

    - Вольное домашнее задание: из [задач к семинарам](https://github.com/bdemeshev/metrics_pro/raw/master/metrics_pro.pdf): 1.1 (2), 1.8, 1.10, 1.12-1.15, 2.1, 2.2, 3.2, 3.3.

* Встреча 2. Обсуждение домашки, SVD, постановка задачи PCA.

    - Конспект Марины Ермоловой: [pdf](https://github.com/bdemeshev/em611/raw/master/2018/notes/seminar_02.pdf), [tex](https://github.com/bdemeshev/em611/raw/master/2018/notes/seminar_02.tex)

    - Вольное домашнее задание: из [задачника по машинке](https://github.com/bdemeshev/mlearn_pro/raw/master/mlearn_pro.pdf)  5.3, 5.14, 5.8, 5.9, 5.10, 5.13.

* Встреча 3. Эквивалентность PCA и SVD.

    - Конспект Лизы Вахрамеевой: [pdf](https://github.com/bdemeshev/em611/raw/master/2018/notes/seminar_03.pdf), [tex](https://github.com/bdemeshev/em611/raw/master/2018/notes/seminar_03.tex)

* Встреча 4. Работа с ковариационными матрицами, геометрическое доказательство теоремы Гаусса-Маркова, проверка гипотез о коэффициенте и сравнение двух моделей

    - Конспект Ефим Лубошников: [pdf](https://github.com/bdemeshev/em611/raw/master/2018/notes/seminar_04.pdf), [tex](https://github.com/bdemeshev/em611/raw/master/2018/notes/seminar_04.tex)
    
* Контрольная работа 1: [2018](https://github.com/bdemeshev/em611/raw/master/2018/kr_01/kr_01.pdf), [2017](https://github.com/bdemeshev/em611/raw/master/2017/kr_01/kr_01.pdf)


* Встреча 5. Птички, дифференциальные формы, экспоненциальное, бета и гамма распределения.

    - Конспект (бета) Ярослав Романов: [pdf](https://github.com/bdemeshev/em611/raw/master/2018/notes/seminar_05.pdf), [tex](https://github.com/bdemeshev/em611/raw/master/2018/notes/seminar_05.tex)

* Встреча 6. Аксиомы Хершела-Максвелла, нормальное распределение, хи-квадрат.

    - Конспект (бета) Мария Щеголева: [pdf](https://github.com/bdemeshev/em611/raw/master/2018/notes/seminar_06.pdf), [tex](https://github.com/bdemeshev/em611/raw/master/2018/notes/seminar_06.tex)


* Встреча 7. t, F-распределения, Матрица-Мать Всех Регрессий.

    - Конспект (бета) Ирина Долгалева и Дарья Краснова: [pdf](https://github.com/bdemeshev/em611/raw/master/2018/notes/seminar_07.pdf), [tex](https://github.com/bdemeshev/em611/raw/master/2018/notes/seminar_07.tex)

* Встреча 8. Гетероскедастичность и корректировки HC.

    - Конспект (бета) Марк Любимов и Галим Бикбов:
[pdf](https://github.com/bdemeshev/em611/raw/master/2018/notes/seminar_08.pdf), [tex](https://github.com/bdemeshev/em611/raw/master/2018/notes/seminar_08.tex)

* Встреча 9. Распределения из мира проекций и из Пуассоновского потока

    - Конспект (бета) Любовь Корж и Кирилл Пак:
[pdf](https://github.com/bdemeshev/em611/raw/master/2018/notes/seminar_09.pdf), [tex](https://github.com/bdemeshev/em611/raw/master/2018/notes/seminar_09.tex)
